[tools]
# renovate: packageName=rhysd/actionlint extractVersion=^v(?<version>.*)$
actionlint = "1.7.8"
# renovate: packageName=golang/go extractVersion=^go(?<version>.*)$
go = "1.25.3"
# renovate: packageName=golangci/golangci-lint extractVersion=^v(?<version>.*)$
golangci-lint = "2.5.0"
# renovate: packageName=evilmartians/lefthook extractVersion=^v(?<version>.*)$
"asdf:jtzero/asdf-lefthook" = { version = "1.13.6", postinstall = "lefthook install" }
# renovate: packageName=pipxproject/pipx extractVersion=^(?<version>.*)$
pipx = "1.8.0"
# renovate: packageName=pre-commit/pre-commit-hooks
"pipx:pre-commit/pre-commit-hooks" = "v6.0.0"
# renovate: packageName=koalaman/shellcheck extractVersion=^v(?<version>.*)$
shellcheck = "0.11.0"
